# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build Backend-fcs-final
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.13.0

      - name: Build Node assets
        env:
          CI: true
          CLOUDINARY_API_KEY: 974646778797368
          CLOUDINARY_API_SECRET: Y0LbzqQ2rG8EoldmpeVw7BYcV_0
          CLOUDINARY_NAME : dlnrtlftr
          DB_URI: mongodb+srv://FCS:FCS123456@cluster0.mml3pm2.mongodb.net/?retryWrites=true&w=majority
          GMAIL_MAIL: fcs.lavage22@gmail.com
          GMAIL_PASSWORD: qmtwxojtafnmviyf
          PORT : 9876
          REDIS_HOST: redis-18515.c55.eu-central-1-1.ec2.cloud.redislabs.com
          REDIS_PASSWORD: fcsdbredis
          REDIS_PORT : 18515
          SCRT_KEY: MYSECRETKEY
          SITE_URL: ${{ inputs.site-url }}
        run: npm ci

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 082c6ab2-cbe8-4cca-b7a3-3e9c55307e72
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Backend-fcs-final/config.yaml
          action: upload
